bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM305_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM292_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM164_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM317_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM271_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB017_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB016_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM300_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM012_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM346_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM354_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM302_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM269_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM125_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM303_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM273_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM325_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM092_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM018_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM208_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM076_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM093_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP068_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM314_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM245_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM143_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM244_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM146_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM114_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM074_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM078_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM015_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM355_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM032_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM313_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM310_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM044_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM322_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP067_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB034_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB021_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM118_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM270_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB014_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM299_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM342_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP014_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM099_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB019_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM192_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM236_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM105_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM046_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM339_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP076_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB012_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM124_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM214_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM312_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM284_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM108_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM282_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM304_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB023_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM283_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP063_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP053_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP070_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM220_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM115_bwa_sorted.bam &
wait
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM345_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP017_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/KP034_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM275_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/BB035_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM142_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM141_bwa_sorted.bam &
bash NYU_pipeline.sh /home/vdp5/projects/vivax_cambodia/data/sequences_bam/OM296_bwa_sorted.bam &
